{
 "title": "Trustify Performance Copy",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Trustify - Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API request latency p99 (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, http_route) (rate(http_server_duration_seconds_bucket{job=\"trustify\"}[10m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API request throughput (requests/sec)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (http_route) (rate(http_server_duration_seconds_count{job=\"trustify\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Trustify - SLOs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Percentage of requests that failed (status code = 4xx | 5xx)",
   "type": "timeseries",
   "description": "Percentage of requests that failed (status code = 4xx | 5xx) (Lower is better).",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by (job) (\n  rate(http_server_duration_seconds_count{http_response_status_code=~\"4..|5..\", job=\"trustify\"}[10m])\n)\n/\nsum by (job) (\n  rate(http_server_duration_seconds_count{http_response_status_code!~\"4..|5..\", job=\"trustify\"}[10m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percentage of the search request response times above 1s",
   "type": "timeseries",
   "description": "Percentage of the search request response times above 1s (Lower is better).",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "1.0 - (sum(rate(http_server_duration_seconds_bucket{http_route=~\"/api/v2/purl\", job = \"trustify\", status !~ \"5..\", le=\"1\"}[10m])) by (job) / sum(rate(http_server_duration_seconds_bucket{http_route=~\"/api/v2/purl\", job = \"trustify\", status !~ \"5..\"}[10m])) by (job))",
     "legendFormat": "PURL"
    },
    {
     "expr": "1.0 - (sum(rate(http_server_duration_seconds_bucket{http_route=~\"/api/v2/sbom\", job = \"trustify\", status !~ \"5..\", le=\"1\"}[10m])) by (job) / sum(rate(http_server_duration_seconds_bucket{http_route=~\"/api/v2/sbom\", job = \"trustify\", status !~ \"5..\"}[10m])) by (job))",
     "legendFormat": "SBOM"
    },
    {
     "expr": "1.0 - (sum(rate(http_server_duration_seconds_bucket{http_route=~\"/api/v2/sbom-labels\", job = \"trustify\", status !~ \"5..\", le=\"1\"}[10m])) by (job) / sum(rate(http_server_duration_seconds_bucket{http_route=~\"/api/v2/sbom-labels\", job = \"trustify\", status !~ \"5..\"}[10m])) by (job))",
     "legendFormat": "SBOM Labels"
    },
    {
     "expr": "1.0 - (sum(rate(http_server_duration_seconds_bucket{http_route=~\"/api/v2/Vulnerability\", job = \"trustify\", status !~ \"5..\", le=\"1\"}[10m])) by (job) / sum(rate(http_server_duration_seconds_bucket{http_route=~\"/api/v2/vulnerability\", job = \"trustify\", status !~ \"5..\"}[10m])) by (job))",
     "legendFormat": "Vulnerability"
    },
    {
     "expr": "1.0 - (sum(rate(http_server_duration_seconds_bucket{http_route=~\"/api/v2/advisory\", job = \"trustify\", status !~ \"5..\", le=\"1\"}[10m])) by (job) / sum(rate(http_server_duration_seconds_bucket{http_route=~\"/api/v2/advisory\", job = \"trustify\", status !~ \"5..\"}[10m])) by (job))",
     "legendFormat": "Advisory"
    },
    {
     "expr": "1.0 - (sum(rate(http_server_duration_seconds_bucket{http_route=~\"/api/v2/advisory-labels\", job = \"trustify\", status !~ \"5..\", le=\"1\"}[10m])) by (job) / sum(rate(http_server_duration_seconds_bucket{http_route=~\"/api/v2/advisory-labels\", job = \"trustify\", status !~ \"5..\"}[10m])) by (job))",
     "legendFormat": "Advisory Labels"
    }
   ]
  }
 ]
}