= TPA v1 to v2 Migration Guide
:source-language: javascript

Do you have to try TPA v2 (a.k.a. Trustify) but your applications and use cases
still depend on TPA v1 (a.k.a. Trustification)? No problem! In this guide, we
show you how to migrate your applications and use cases to TPA v2. Just choose
from the sections below, depending on what part of TPA v1 you wish to migrate.

In the examples below:

* `bombastic` is an `axios` wrapper around TPA v1 Bombastic endpoint
* `trustify` is an `axios` wrapper around TPA v2 endpoint
* `topdir` refers to the top directory of the
  link:https://github.com/trustification/trustify[`trustify` upstream repository]
* `assert`, `crypto`, `fs`, and `path` are standard Node.js libraries

== SBOM API

=== Ingesting an SBOM File

In TPA v1, you upload SBOM file like this:
[%test]
----
const sbomId = "my-sbom";
const sbomFile = path.join(topdir, "etc/test-data/spdx/simple.json");

// Raise an exception if `sbomFile` does not exist
fs.statSync(sbomFile);

const payload = fs.readFileSync(sbomFile);

(async () => {
  await bombastic.post(`/api/v1/sbom?id=${sbomId}`, payload, {
    headers: { "Content-Type": "application/json" }
  });

  const { data } = await bombastic.get(`/api/v1/sbom?id=${sbomId}`);

  assert.deepStrictEqual(data, JSON.parse(payload));
})();
----

In TPA v2, using `id` to name your SBOMs is no longer possible. When an SBOM is
uploaded, the special UUID is generated and attached to it. This UUID is
returned as a part of the response, so you can use it later for downloading the
SBOM.

However, you can also use one of three checksum (SHA256, SHA384, SHA512) to
download your SBOM. This can be used as a workaround to the TPA v1 use case
since the checksum can be computed before the SBOM is uploaded:
[%test]
----
const sbomFile = path.join(topdir, "etc/test-data/spdx/simple.json");

// Raise an exception if `sbomFile` does not exist
fs.statSync(sbomFile);

const payload = fs.readFileSync(sbomFile);

const sha512 = crypto.createHash("sha512").update(payload).digest("hex");

(async () => {
  await trustify.post("/api/v2/sbom", payload, {
    headers: { "Content-Type": "application/json" }
  });

  const { data } = await trustify.get(`/api/v2/sbom/sha512:${sha512}/download`);

  assert.deepStrictEqual(data, JSON.parse(payload));
})();
----
