ALTER TABLE ONLY public.version_range DROP CONSTRAINT version_range_version_scheme_id_fkey;
ALTER TABLE ONLY public.sbom DROP CONSTRAINT sbom_source_document_id_fkey;
ALTER TABLE ONLY public.sbom_package DROP CONSTRAINT sbom_package_sbom_id_fkey;
ALTER TABLE ONLY public.sbom_package_purl_ref DROP CONSTRAINT sbom_package_purl_ref_sbom_id_node_id_fkey;
ALTER TABLE ONLY public.sbom_package_purl_ref DROP CONSTRAINT sbom_package_purl_ref_qualified_package_id_fkey;
ALTER TABLE ONLY public.sbom_package_cpe_ref DROP CONSTRAINT sbom_package_cpe_ref_sbom_id_node_id_fkey;
ALTER TABLE ONLY public.sbom_package_cpe_ref DROP CONSTRAINT sbom_package_cpe_ref_cpe_id_fkey;
ALTER TABLE ONLY public.sbom_node DROP CONSTRAINT sbom_node_sbom_id_fkey;
ALTER TABLE ONLY public.sbom_file DROP CONSTRAINT sbom_file_sbom_id_fkey;
ALTER TABLE ONLY public.qualified_purl DROP CONSTRAINT qualified_package_package_version_id_fkey;
ALTER TABLE ONLY public.purl_status DROP CONSTRAINT purl_status_cpe_fk;
ALTER TABLE ONLY public.purl_status DROP CONSTRAINT purl_status_advisory_id_fkey;
ALTER TABLE ONLY public.purl_license_assertion DROP CONSTRAINT purl_license_assertion_versioned_purl_id_fkey;
ALTER TABLE ONLY public.purl_license_assertion DROP CONSTRAINT purl_license_assertion_sbom_id_fkey;
ALTER TABLE ONLY public.purl_license_assertion DROP CONSTRAINT purl_license_assertion_license_id_fkey;
ALTER TABLE ONLY public.product_version DROP CONSTRAINT product_version_sbom_id_fkey;
ALTER TABLE ONLY public.product_version_range DROP CONSTRAINT product_version_range_version_range_id_fkey;
ALTER TABLE ONLY public.product_version_range DROP CONSTRAINT product_version_range_product_id_fkey;
ALTER TABLE ONLY public.product_version DROP CONSTRAINT product_version_product_id_fkey;
ALTER TABLE ONLY public.product DROP CONSTRAINT product_vendor_id_fkey;
ALTER TABLE ONLY public.product_status DROP CONSTRAINT product_status_vulnerability_id_fkey;
ALTER TABLE ONLY public.product_status DROP CONSTRAINT product_status_status_id_fkey;
ALTER TABLE ONLY public.product_status DROP CONSTRAINT product_status_product_version_range_id_fkey;
ALTER TABLE ONLY public.product_status DROP CONSTRAINT product_status_context_cpe_id_fkey;
ALTER TABLE ONLY public.product_status DROP CONSTRAINT product_status_advisory_id_fkey;
ALTER TABLE ONLY public.versioned_purl DROP CONSTRAINT package_version_package_id_fkey;
ALTER TABLE ONLY public.purl_status DROP CONSTRAINT package_status_version_range_id_fkey;
ALTER TABLE ONLY public.purl_status DROP CONSTRAINT package_status_status_id_fkey;
ALTER TABLE ONLY public.purl_status DROP CONSTRAINT package_status_package_id_fkey;
ALTER TABLE ONLY public.package_relates_to_package DROP CONSTRAINT package_relates_to_package_sbom_id_right_node_id_fkey;
ALTER TABLE ONLY public.package_relates_to_package DROP CONSTRAINT package_relates_to_package_sbom_id_left_node_id_fkey;
ALTER TABLE ONLY public.package_relates_to_package DROP CONSTRAINT package_relates_to_package_sbom_id_fkey;
ALTER TABLE ONLY public.package_relates_to_package DROP CONSTRAINT package_relates_to_package_relationship_fkey;
ALTER TABLE ONLY public.importer_report DROP CONSTRAINT importer_report_importer_fkey;
ALTER TABLE ONLY public.vulnerability_description DROP CONSTRAINT fk_adv_vuln;
ALTER TABLE ONLY public.cpe_license_assertion DROP CONSTRAINT cpe_license_assertion_sbom_id_fkey;
ALTER TABLE ONLY public.cpe_license_assertion DROP CONSTRAINT cpe_license_assertion_license_id_fkey;
ALTER TABLE ONLY public.cpe_license_assertion DROP CONSTRAINT cpe_license_assertion_cpe_id_fkey;
ALTER TABLE ONLY public.advisory_vulnerability DROP CONSTRAINT advisory_vulnerability_advisory_id_fkey;
ALTER TABLE ONLY public.advisory DROP CONSTRAINT advisory_source_document_id_fkey;
ALTER TABLE ONLY public.advisory DROP CONSTRAINT advisory_issuer_id_fkey;
DROP INDEX public.versioned_purl_id_idx;
DROP INDEX public.versioned_purl_base_purl_id_idx;
DROP INDEX public.sha512_index;
DROP INDEX public.sha384_index;
DROP INDEX public.sha256_index;
DROP INDEX public.sbomnodenameginidx;
DROP INDEX public.sbom_package_sbom_id_node_id_idx;
DROP INDEX public.sbom_package_sbom_id_idx;
DROP INDEX public.sbom_package_purl_ref_sbom_id_idx;
DROP INDEX public.sbom_package_purl_ref_qual_purl_id_idx;
DROP INDEX public.sbom_package_purl_ref_node_id_idx;
DROP INDEX public.sbom_node_sbom_id_node_id_idx;
DROP INDEX public.sbom_node_sbom_id_idx;
DROP INDEX public.sbom_labels_idx;
DROP INDEX public.sbom_external_node_external_node_ref_idx;
DROP INDEX public.sbom_external_node_external_doc_ref_idx;
DROP INDEX public.qualifiedpurlversionjsongistidx;
DROP INDEX public.qualifiedpurltypejsongistidx;
DROP INDEX public.qualifiedpurlqualifierrepositoryurljsonginidx;
DROP INDEX public.qualifiedpurlqualifierdistrojsonsortidx;
DROP INDEX public.qualifiedpurlqualifierdistrojsonginidx;
DROP INDEX public.qualifiedpurlqualifierarchjsonsortidx;
DROP INDEX public.qualifiedpurlqualifierarchjsonginidx;
DROP INDEX public.qualifiedpurlpurlversionjsonsortidx;
DROP INDEX public.qualifiedpurlpurlversionjsonginidx;
DROP INDEX public.qualifiedpurlpurltyjsonsortidx;
DROP INDEX public.qualifiedpurlpurltyjsonginidx;
DROP INDEX public.qualifiedpurlpurlnamespacejsonsortidx;
DROP INDEX public.qualifiedpurlpurlnamespacejsonginidx;
DROP INDEX public.qualifiedpurlpurlnamejsonsortidx;
DROP INDEX public.qualifiedpurlpurlnamejsonginidx;
DROP INDEX public.qualifiedpurlnamespacejsongistidx;
DROP INDEX public.qualifiedpurlnamejsongistidx;
DROP INDEX public.qualified_purl_id_idx;
DROP INDEX public.purl_status_vuln_id_idx;
DROP INDEX public.purl_status_combo_idx;
DROP INDEX public.purl_status_base_purl_id_idx;
DROP INDEX public.product_status_idx;
DROP INDEX public.package_status_idx;
DROP INDEX public.not_deprecated;
DROP INDEX public.name_index;
DROP INDEX public.cvss4_vuln_id_idx;
DROP INDEX public.cvss4_adv_id_idx;
DROP INDEX public.cvss3_vuln_id_idx;
DROP INDEX public.cvss3_adv_id_vuln_id_minor_version_idx;
DROP INDEX public.cvss3_adv_id_idx;
DROP INDEX public.by_pvid;
DROP INDEX public.by_productid_v;
DROP INDEX public.by_pid_v;
DROP INDEX public.by_id_and_version;
DROP INDEX public.basepurltypeginidx;
DROP INDEX public.basepurlnamespaceginidx;
DROP INDEX public.basepurlnameginidx;
DROP INDEX public.base_purl_id_idx;
DROP INDEX public.advisory_vulnerability_advisory_id_idx;
DROP INDEX public.advisory_labels_idx;
DROP INDEX public.advisory_id_index;
ALTER TABLE ONLY public.weakness DROP CONSTRAINT weakness_pkey;
ALTER TABLE ONLY public.vulnerability DROP CONSTRAINT vulnerability_pkey;
ALTER TABLE ONLY public.vulnerability_description DROP CONSTRAINT vulnerability_description_pkey;
ALTER TABLE ONLY public.version_scheme DROP CONSTRAINT version_scheme_pkey;
ALTER TABLE ONLY public.version_range DROP CONSTRAINT version_range_pkey;
ALTER TABLE ONLY public.user_preferences DROP CONSTRAINT user_preferences_pkey;
ALTER TABLE ONLY public.status DROP CONSTRAINT status_pkey;
ALTER TABLE ONLY public.source_document DROP CONSTRAINT source_document_pkey;
ALTER TABLE ONLY public.sbom DROP CONSTRAINT sbom_pkey;
ALTER TABLE ONLY public.sbom_package_purl_ref DROP CONSTRAINT sbom_package_purl_ref_pkey;
ALTER TABLE ONLY public.sbom_package DROP CONSTRAINT sbom_package_pkey;
ALTER TABLE ONLY public.sbom_package_cpe_ref DROP CONSTRAINT sbom_package_cpe_ref_pkey;
ALTER TABLE ONLY public.sbom_node DROP CONSTRAINT sbom_node_pkey;
ALTER TABLE ONLY public.sbom_file DROP CONSTRAINT sbom_file_pkey;
ALTER TABLE ONLY public.sbom_external_node DROP CONSTRAINT sbom_external_node_pkey;
ALTER TABLE ONLY public.relationship DROP CONSTRAINT relationship_pkey;
ALTER TABLE ONLY public.qualified_purl DROP CONSTRAINT qualified_package_pkey;
ALTER TABLE ONLY public.purl_license_assertion DROP CONSTRAINT purl_license_assertion_pkey;
ALTER TABLE ONLY public.purl_license_assertion DROP CONSTRAINT purl_license_assertion_idx;
ALTER TABLE ONLY public.product_version_range DROP CONSTRAINT product_version_range_pkey;
ALTER TABLE ONLY public.product_version DROP CONSTRAINT product_version_pkey;
ALTER TABLE ONLY public.product_status DROP CONSTRAINT product_status_pkey;
ALTER TABLE ONLY public.product DROP CONSTRAINT product_pkey;
ALTER TABLE ONLY public.versioned_purl DROP CONSTRAINT package_version_pkey;
ALTER TABLE ONLY public.base_purl DROP CONSTRAINT package_type_namespace_name_key;
ALTER TABLE ONLY public.purl_status DROP CONSTRAINT package_status_pkey;
ALTER TABLE ONLY public.package_relates_to_package DROP CONSTRAINT package_relates_to_package_pkey;
ALTER TABLE ONLY public.base_purl DROP CONSTRAINT package_pkey;
ALTER TABLE ONLY public.organization DROP CONSTRAINT organization_pkey;
ALTER TABLE ONLY public.license DROP CONSTRAINT license_pkey;
ALTER TABLE ONLY public.importer_report DROP CONSTRAINT importer_report_pkey;
ALTER TABLE ONLY public.importer DROP CONSTRAINT importer_pkey;
ALTER TABLE ONLY public.cpe DROP CONSTRAINT cpe_pkey;
ALTER TABLE ONLY public.cpe_license_assertion DROP CONSTRAINT cpe_license_assertion_pkey;
ALTER TABLE ONLY public.cpe_license_assertion DROP CONSTRAINT cpe_license_assertion_idx;
ALTER TABLE ONLY public.advisory_vulnerability DROP CONSTRAINT advisory_vulnerability_pkey;
ALTER TABLE ONLY public.advisory DROP CONSTRAINT advisory_uuid_key;
ALTER TABLE ONLY public.advisory DROP CONSTRAINT advisory_pkey;
DROP TABLE public.weakness;
DROP TABLE public.vulnerability_description;
DROP TABLE public.vulnerability;
DROP TABLE public.versioned_purl;
DROP TABLE public.version_scheme;
DROP TABLE public.user_preferences;
DROP TABLE public.status;
DROP TABLE public.source_document;
DROP TABLE public.sbom_package_purl_ref;
DROP TABLE public.sbom_package_cpe_ref;
DROP TABLE public.sbom_package;
DROP TABLE public.sbom_node;
DROP TABLE public.sbom_file;
DROP TABLE public.sbom_external_node;
DROP TABLE public.sbom;
DROP TABLE public.relationship;
DROP TABLE public.qualified_purl;
DROP TABLE public.purl_status;
DROP TABLE public.purl_license_assertion;
DROP TABLE public.product_version_range;
DROP TABLE public.product_version;
DROP TABLE public.product_status;
DROP TABLE public.product;
DROP TABLE public.package_relates_to_package;
DROP TABLE public.organization;
DROP TABLE public.license;
DROP TABLE public.importer_report;
DROP TABLE public.importer;
DROP TABLE public.cvss4;
DROP TABLE public.cpe_license_assertion;
DROP TABLE public.cpe;
DROP TABLE public.base_purl;
DROP TABLE public.advisory_vulnerability;
DROP TABLE public.advisory;
DROP FUNCTION public.version_matches(version_p text, range_p public.version_range);
DROP FUNCTION public.update_deprecated_advisory(identifier_input text);
DROP FUNCTION public.semver_version_matches(version_p text, range_p public.version_range);
DROP FUNCTION public.semver_lte(left_p text, right_p text);
DROP FUNCTION public.semver_lt(left_p text, right_p text);
DROP FUNCTION public.semver_gte(left_p text, right_p text);
DROP FUNCTION public.semver_gt(left_p text, right_p text);
DROP FUNCTION public.semver_eq(left_p text, right_p text);
DROP FUNCTION public.semver_cmp(left_p text, right_p text);
DROP FUNCTION public.rpmver_version_matches(version_p text, range_p public.version_range);
DROP FUNCTION public.rpmver_cmp(a text, b text);
DROP FUNCTION public.qualified_package_transitive(sbom_id_param uuid, start_qualified_purl_id uuid, relationships_param integer[]);
DROP FUNCTION public.pythonver_cmp(left_p text, right_p text);
DROP FUNCTION public.python_version_matches(version_p text, range_p public.version_range);
DROP FUNCTION public.package_transitive(sbom_id_param uuid, start_node_id text, relationships_param integer[]);
DROP FUNCTION public.mavenver_cmp(left_p text, right_p text);
DROP FUNCTION public.maven_version_matches(version_p text, range_p public.version_range);
DROP FUNCTION public.is_numeric(str text);
DROP FUNCTION public.gitver_version_matches(version_p text, range_p public.version_range);
DROP FUNCTION public.get_purl(qualified_purl_id uuid);
DROP FUNCTION public.generic_version_matches(version_p text, range_p public.version_range);
DROP TABLE public.version_range;
DROP FUNCTION public.encode_uri_component(text);
DROP FUNCTION public.cvss3_ui_score(ui_p public.cvss3_ui);
DROP FUNCTION public.cvss3_severity(score_p double precision);
DROP FUNCTION public.cvss3_score(cvss3_p public.cvss3);
DROP FUNCTION public.cvss3_scope_changed(s_p public.cvss3_s);
DROP FUNCTION public.cvss3_pr_scoped_score(pr_p public.cvss3_pr, scope_changed_p boolean);
DROP FUNCTION public.cvss3_impact(cvss3_p public.cvss3);
DROP FUNCTION public.cvss3_i_score(i_p public.cvss3_i);
DROP FUNCTION public.cvss3_exploitability(cvss3_p public.cvss3);
DROP TABLE public.cvss3;
DROP FUNCTION public.cvss3_c_score(c_p public.cvss3_c);
DROP FUNCTION public.cvss3_av_score(av_p public.cvss3_av);
DROP FUNCTION public.cvss3_ac_score(ac_p public.cvss3_ac);
DROP FUNCTION public.cvss3_a_score(a_p public.cvss3_a);
DROP TYPE public.cvss4_vi;
DROP TYPE public.cvss4_vc;
DROP TYPE public.cvss4_va;
DROP TYPE public.cvss4_ui;
DROP TYPE public.cvss4_si;
DROP TYPE public.cvss4_sc;
DROP TYPE public.cvss4_sa;
DROP TYPE public.cvss4_pr;
DROP TYPE public.cvss4_av;
DROP TYPE public.cvss4_at;
DROP TYPE public.cvss4_ac;
DROP TYPE public.cvss3_ui;
DROP TYPE public.cvss3_severity;
DROP TYPE public.cvss3_s;
DROP TYPE public.cvss3_pr;
DROP TYPE public.cvss3_i;
DROP TYPE public.cvss3_c;
DROP TYPE public.cvss3_av;
DROP TYPE public.cvss3_ac;
DROP TYPE public.cvss3_a;
DROP EXTENSION pg_trgm;
